### ISSUE TITLE
Regenerate time zone data resources for 2014j

### ISSUE THREAD

**Issue by arminha** [dlew/joda-time-android#29] opened 2015-02-02 20:14 UTC
joda-time 2.7 fixed a bug in the ZoneInfoCompiler, which resulted in incorrect time zone files. (See https://github.com/JodaOrg/joda-time/issues/208)
joda-time-android still includes incorrect files. Regenerating them with joda-time 2.7 should fix that.

**Comment by dlew** [comment] 2015-02-10 01:35
This is a duplicate of #27

**Closed by dlew** 2015-02-10 01:35 UTC
