### ISSUE TITLE
Not able to see documentation

### ISSUE THREAD

**Issue by krupalagile** [dlew/joda-time-android#185] opened 2017-07-08 12:10 UTC
I don't find any doc comments over library functions. Can you please add it?

**Comment by TakWolf** [comment] 2017-07-08 14:00
This library is a version of Joda-Time built with Android in mind.
About joda-Time api, see https://github.com/JodaOrg/joda-time.

Others, see this project's readme.

**Comment by dlew** [comment] 2017-07-10 15:58
Closing as a duplicate of #25.

**Closed by dlew** 2017-07-10 15:58 UTC
