### ISSUE TITLE
Could not read ZoneInfoMap. You are probably using Proguard wrong.

### ISSUE THREAD

**Issue by alexhorsa** [dlew/joda-time-android#206] opened 2018-09-12 09:20 UTC
Hi,

This is the stacktrace without any proguard rules
```
Caused by: java.lang.RuntimeException: Could not read ZoneInfoMap. You are probably using Proguard wrong.
                                                       at net.danlew.android.joda.a.a(JodaTimeAndroid.java:42)
```

```
Failed to retrieve identifier: type=class net.danlew.android.joda.b$a name=joda_zoneinfomap
                                                    java.lang.NoSuchFieldException: joda_zoneinfomap
                                                        at java.lang.Class.getField(Class.java:891)
                                                        at net.danlew.android.joda.c.a(ResUtils.java:105)
                                                        at net.danlew.android.joda.d.a(ResourceZoneInfoProvider.java:113)
                                                        at net.danlew.android.joda.d.<init>(ResourceZoneInfoProvider.java:38)
                                                        at net.danlew.android.joda.a.a(JodaTimeAndroid.java:39)
```

Using these rules solve the problem but I wonder what do you recommend
```
-dontwarn org.joda.convert.**
-dontwarn org.joda.time.**
-keep class org.joda.time.** { *; }
-keep interface org.joda.time.** { *; }
-keep class net.danlew.** { *; }
```

**Comment by alexhorsa** [comment] 2018-09-13 08:16
Hmm, I am not aware of removing anything. I don't even know how to remove things with Proguard. What should I look for?

**Comment by dlew** [comment] 2018-09-13 18:50
Well, in particular, it looks like the minifier is removing the resource `joda_zoneinfomap`. That should be kept, as per our resource keep rules: https://github.com/dlew/joda-time-android/blob/master/library/src/main/res/raw/joda_keep.xml

**Comment by DmitryGlotov** [comment] 2018-10-24 16:34
Happened for me too, @alexhorsa 's proguard rules did the job,
that is very strange because I didn't changing anything and today it is stop working.
I'm using D8/R8 and Android Studio 3.3 Canary 13 for a while.

**Comment by agap** [comment] 2018-11-14 06:31
Happened to me as well, Android Studio 3.2.1.
I am pretty sure I wasn't updating any proguard rules for at least as long as 2-3 months.

**Comment by EdwardQuixote** [comment] 2019-01-09 07:35
Well, @dlew in my case, I can't disable Minify because I'm use a great number of Google libraries and together, number of methods called exceeds the set limits.
So @alexhorsa Proguard rules work for my case.

However, disable Minify also works, but I can't rely on that solution on production environment.

**Comment by gr3ger** [comment] 2019-10-01 10:57
I'm getting this issue as well, turning off minify is sadly something I can't do on production.
I think it started happening after I upgraded AGP to 3.5.0 and target SDK to 28

**Comment by zhukic** [comment] 2019-10-07 14:14
Hi. 
It seems that R8 removes static final fields from `R.raw` class. Resources are presented in the build, but when you [try](https://github.com/dlew/joda-time-android/blob/master/library/src/main/java/net/danlew/android/joda/ResourceZoneInfoProvider.java#L113) to get resource identifier via reflection, it can't be found because it was removed during shrinking and we get `java.lang.NoSuchFieldException: joda_zoneinfomap`.

**Comment by Nitnatsnok** [comment] 2020-01-21 12:49
Hello. I faced the same problem. I solved this by adding one rule
`-keep class net.danlew.android.joda.R$raw { *; }`

**Comment by ricowind** [comment] 2020-04-22 07:31
AGP no longer has the keep rule of the form:
-keepclassmembers class **.R$* {
   public static <fields>;
}
This was only there to support the resource shrinker (which is now using R.txt to get resource ids)
It is important for other optimizations that we don't keep all the fields in the R class.

Can I as _why_ you are looking up these using reflection? If you absolutely need to, you could instead use Resources.getIdentifier calls.

**Comment by dlew** [comment] 2020-04-22 19:56
Using `Resources.getIdentifier()` isn't going to help this situation. If the issue is that Proguard/R8 is removing resources, then any form of dynamic retrieval will fail.

Thanks for pointing out the root problem - I did not realize that AGP's rules had changed. We can incorporate a fix that keeps just joda-time-android's R files.

(PS - It's using reflection because [it's faster than `Resources.getIdentifier()`](https://blog.danlew.net/2009/12/27/dynamically_retrieving_resources_in_android/).)

**Comment by ricowind** [comment] 2020-04-23 05:20
> Using `Resources.getIdentifier()` isn't going to help this situation. If the issue is that Proguard/R8 is removing resources, then any form of dynamic retrieval will fail.
So what happens is not that R8 is removing the resource (it will never remove any resource, it only touches code). What happens is that R8 is removing the R$raw class fields because it has inlined those constants. The R classes only contains integer values that are "pointers" into the resources.arsc file in your apk. These will be inlined by R8, but before, the keep rule from AGP would ensure that all fields of all R classes was kept (for resource shrinking to work, but that is actually besides the point here).
Resources.getIdentifier() does _not_ use the R class to lookup entries, it uses the resources.arsc table. 

The keep rule you have in your XML file is only used for resource shrinking (not R8, which is code shrinking).

**Comment by ricowind** [comment] 2020-04-30 08:38
Could we put in that keep rule and do a new release, we expect this to actually start breaking people with android studio 4.1

**Comment by dlew** [comment] 2020-04-30 13:51
There's been a new tzdata release recently anyways, so I'm planning to fix both this and update the tzdata sometime this week.

**Closed** 2020-05-03 20:32 UTC
