### ISSUE TITLE
lower case?

### ISSUE THREAD

**Issue by AshkanImmortal** [dlew/joda-time-android#49] opened 2015-06-01 08:28 UTC
Error:Execution failed for task ':app:mergeDebugResources'.
> /path _to_app/Source/app/build/intermediates/exploded-aar/net.danlew/android.joda/2.7.2/res/raw/__tzdata_africa_abidjan: Error: File-based resource names must start with a lowercase letter

**Comment by dlew** [comment] 2015-06-01 11:37
Duplicate of #46

**Closed by dlew** 2015-06-01 11:37 UTC
