### ISSUE TITLE
DateTimeFormat.parseDateTime throws IllegalArgumentException only on Android 12

### ISSUE THREAD

**Issue by nlasagni** [dlew/joda-time-android#297] opened 2022-02-02 17:48 UTC
Hi, I have defined a JSON serializer as follows:
```kotlin
 DateTimeJsonConverter : JsonSerializer<DateTime>, JsonDeserializer<DateTime>
```

The `DateTimeJsonConverter` is registered as a `TypeAdapter` to `Gson`, which is used by Retrofit in order to serialize/deserialize JSON coming from APIs responses:

```kotlin
        GsonBuilder()
            ...
            .registerTypeAdapter(DateTime::class.java, DateTimeJsonConverter())
            ...
            .create()
```

The `DateTimeJsonConverter` uses a `DateTimeFormat` in order to serialize and desirialize dates:
```kotlin
     private val dateTimeFormatter = DateTimeFormat
        .forPattern("EEE, dd MMM yyyy HH:mm:ss 'GMT'")
        .withZoneUTC()
        .withLocale(Locale.UK)
```

The issue is that when the `DateTimeJsonConverter` calls `dateTimeFormatter.parseDateTime(str)` on the following string "Thu, 30 Sep 2021 22:00:00 GMT", an exception is thrown only on Android 12. 

The exception is the following: `java.lang.IllegalArgumentException: Invalid format: "Thu, 30 Sep 2021 22:00:00 GMT" is malformed at "Sep 2021 22:00:00 GMT"`

Inside the JSON string which contains that string there are also other strings in the same format (e.g. "Sun, 31 Oct 2021 23:00:00 GMT") that don't cause an exception. 

NOTE: I'm currently using the latest version of the library, `2.10.12.2`.

**Comment by dlew** [comment] 2022-02-02 23:03
I've taken a look and the root cause is that `Locale.UK` expects `Sept` in Android 12 but `Sep` pre-12. Ouch!

You can check which symbols are valid short month names using this: `DateFormatSymbols.getInstance(Locale.UK).shortMonths`.

My suggestion is to use `Locale.ENGLISH` because it is consistently `Sep` for all versions, as far as I can tell.

I'm closing this out because it's not the fault of joda-time or joda-time-android, rather a change with the underlying system `Locale` which we don't have any control over.

**Closed by dlew** 2022-02-02 23:03 UTC
